/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * AI 旅游攻略智能体的行程输出契约：大模型生成层必须产出符合本结构的 JSON，前端渲染层只消费本结构。
 */
export interface TravelItinerary {
  /**
   * 可选，契约版本号，由后端注入
   */
  schemaVersion?: string;
  trip: {
    /**
     * 行程标题，如「秋日上海 · 三日行程」
     */
    title: string;
    city: string;
    /**
     * 如 11月20日
     */
    dateStart: string;
    /**
     * 如 11月22日
     */
    dateEnd: string;
    daysCount: number;
    /**
     * 概览统计条：天数 / 地点数 / 人均预算 / 日均步数等
     *
     * @minItems 2
     * @maxItems 6
     */
    stats:
      | [
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          }
        ]
      | [
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          }
        ]
      | [
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          }
        ]
      | [
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          }
        ]
      | [
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          }
        ];
  };
  /**
   * 每天一个主题（区域线索，如「老城厢」「梧桐区」），不是景点罗列；同一天内地点地理上顺路。
   *
   * @minItems 1
   */
  days: [
    {
      day: number;
      /**
       * 区域主题标签，如「DAY 1 · 老城厢」
       */
      theme: string;
      /**
       * 当天主目的地，如「外滩 · 豫园」
       */
      title: string;
      /**
       * @minItems 3
       * @maxItems 8
       */
      items:
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            }
          ];
      /**
       * 今日餐饮：KB 真实餐厅推荐（系统挂载，格式：午餐「X」· 晚餐「Y」）
       */
      eat: string;
      /**
       * 建议住宿：真实酒店/民宿名称（可含区域说明），如「桂林香格里拉大酒店」
       */
      stay?: string;
    },
    ...{
      day: number;
      /**
       * 区域主题标签，如「DAY 1 · 老城厢」
       */
      theme: string;
      /**
       * 当天主目的地，如「外滩 · 豫园」
       */
      title: string;
      /**
       * @minItems 3
       * @maxItems 8
       */
      items:
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
              /**
               * 门票价格区间，后端从知识库注入，非模型输出
               */
              price_range?: {
                min?: number;
                max?: number;
              };
              /**
               * 价格数据来源，如'高德POI'或'估算（基于价格等级）'
               */
              price_source?: string;
              /**
               * 价格数据更新时间 ISO 日期，如'2026-07-21'
               */
              price_updated_at?: string;
              /**
               * 预订/查看实时价格跳转链接
               */
              booking_url?: string;
            }
          ];
      /**
       * 今日餐饮：KB 真实餐厅推荐（系统挂载，格式：午餐「X」· 晚餐「Y」）
       */
      eat: string;
      /**
       * 建议住宿：真实酒店/民宿名称（可含区域说明），如「桂林香格里拉大酒店」
       */
      stay?: string;
    }[]
  ];
  /**
   * 分类花费预估，用于渲染进度条。amount 各项加总必须等于人均总预算；percent 为占总额比例，由后端从 amount 计算注入（模型只需输出 amount）。
   *
   * @minItems 2
   * @maxItems 8
   */
  budget:
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ]
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ]
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ]
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ]
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ]
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ]
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ];
  /**
   * 行前清单，渲染为可打勾列表；done 一律为 false（后端强制），由用户在前端勾选。
   *
   * @minItems 3
   * @maxItems 12
   */
  checklist:
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ];
  /**
   * 实用提示 chips：具体可执行（写清 App 名/价格/时间），禁止空泛建议。
   *
   * @minItems 2
   * @maxItems 6
   */
  tips:
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string];
  /**
   * 可选，校验报告（后端生成层产出，非模型输出）：POI 存续、路线顺路、天气匹配的结论汇总。
   */
  validation_report?: {
    /**
     * 每个游览点的存续校验结论
     */
    poi: {
      name: string;
      status: "verified" | "unknown" | "closed" | "replaced";
      /**
       * 所属行政区，如 渝中区
       */
      district?: string;
      /**
       * 人类可读的原因说明（未核实/被替换时必填）
       */
      note?: string;
    }[];
    /**
     * 已核实/总游览点，如 10/11
     */
    poi_verified: string;
    /**
     * 每日路线结论
     */
    routes: {
      day: number;
      /**
       * 当日游览点连线总里程（公里）
       */
      total_km?: number;
      /**
       * 是否检测到明显折返（优化器重排过）
       */
      backtrack: boolean;
      note?: string;
    }[];
    /**
     * 汇总级：是否存在折返
     */
    route_backtrack: boolean;
    /**
     * 天气与行程匹配度
     */
    weather_fit: "good" | "fair" | "poor" | "unknown";
    /**
     * 逐日天气匹配说明（如「D1 雷暴日，3 个室内项目」）
     */
    weather_notes?: string[];
    /**
     * 校验日期，如 2026-07-21
     */
    checked_at: string;
  };
  /**
   * 价格汇总，后端注入，非模型输出。用于前端预算对比与价格新鲜度提示。
   */
  price_summary?: {
    total_estimate_min?: number;
    total_estimate_max?: number;
    /**
     * 有价格数据的 POI 数
     */
    priced_items?: number;
    /**
     * 可参观 POI 总数
     */
    total_items?: number;
    /**
     * 价格超过 90 天未更新的 POI 数
     */
    stale_items?: number;
    /**
     * 用户的预算档次，如 经济/适中/舒适
     */
    budget_slot?: string;
    /**
     * 行程花费是否超出用户预算
     */
    over_budget?: boolean;
    /**
     * 超预算时的人类可读提示
     */
    over_budget_warning?: string;
  };
}
