/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * AI 旅游攻略智能体的行程输出契约：大模型生成层必须产出符合本结构的 JSON，前端渲染层只消费本结构。
 */
export interface TravelItinerary {
  /**
   * 可选，契约版本号，由后端注入
   */
  schemaVersion?: string;
  trip: {
    /**
     * 行程标题，如「秋日上海 · 三日行程」
     */
    title: string;
    city: string;
    /**
     * 如 11月20日
     */
    dateStart: string;
    /**
     * 如 11月22日
     */
    dateEnd: string;
    daysCount: number;
    /**
     * 概览统计条：天数 / 地点数 / 人均预算 / 日均步数等
     *
     * @minItems 2
     * @maxItems 6
     */
    stats:
      | [
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          }
        ]
      | [
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          }
        ]
      | [
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          }
        ]
      | [
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          }
        ]
      | [
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          },
          {
            /**
             * 如「3 天」「¥2,400」
             */
            value: string;
            /**
             * 如「人均预算」「预计日均」
             */
            label: string;
          }
        ];
  };
  /**
   * 每天一个主题（区域线索，如「老城厢」「梧桐区」），不是景点罗列；同一天内地点地理上顺路。
   *
   * @minItems 1
   */
  days: [
    {
      day: number;
      /**
       * 区域主题标签，如「DAY 1 · 老城厢」
       */
      theme: string;
      /**
       * 当天主目的地，如「外滩 · 豫园」
       */
      title: string;
      /**
       * @minItems 3
       * @maxItems 8
       */
      items:
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            }
          ];
      /**
       * 每日一味：具体餐厅 + 招牌菜，如「豫园『南翔馒头店』蟹粉小笼」
       */
      eat: string;
    },
    ...{
      day: number;
      /**
       * 区域主题标签，如「DAY 1 · 老城厢」
       */
      theme: string;
      /**
       * 当天主目的地，如「外滩 · 豫园」
       */
      title: string;
      /**
       * @minItems 3
       * @maxItems 8
       */
      items:
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            }
          ]
        | [
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            },
            {
              /**
               * 24 小时制，如 08:30
               */
              time: string;
              /**
               * 地点/活动，需提前预约的要写清
               */
              poi: string;
              /**
               * 一句理由：为什么这个时间点去（人少/光线/场次/闭馆时间等）
               */
              note: string;
            }
          ];
      /**
       * 每日一味：具体餐厅 + 招牌菜，如「豫园『南翔馒头店』蟹粉小笼」
       */
      eat: string;
    }[]
  ];
  /**
   * 分类花费预估，用于渲染进度条。amount 各项加总必须等于人均总预算；percent 为占总额比例，由后端从 amount 计算注入（模型只需输出 amount）。
   *
   * @minItems 2
   * @maxItems 8
   */
  budget:
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ]
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ]
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ]
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ]
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ]
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ]
    | [
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        },
        {
          /**
           * 如 餐饮/门票/交通/购物
           */
          label: string;
          /**
           * 金额（元）
           */
          amount: number;
          percent: number;
        }
      ];
  /**
   * 行前清单，渲染为可打勾列表；done 一律为 false（后端强制），由用户在前端勾选。
   *
   * @minItems 3
   * @maxItems 12
   */
  checklist:
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ]
    | [
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        },
        {
          text: string;
          done?: boolean;
        }
      ];
  /**
   * 实用提示 chips：具体可执行（写清 App 名/价格/时间），禁止空泛建议。
   *
   * @minItems 2
   * @maxItems 6
   */
  tips:
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string];
}
