"""add_itinerary_versions_phase8.3

Revision ID: 9f9b046b899e
Revises: 6e4bd4265e11
Create Date: 2026-07-21 21:16:44.788244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9b046b899e'
down_revision: Union[str, None] = '6e4bd4265e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('itinerary_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('change_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itinerary_id', 'version_number', name='uq_version_per_itinerary')
    )
    op.create_index(op.f('ix_itinerary_versions_itinerary_id'), 'itinerary_versions', ['itinerary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_versions_itinerary_id'), table_name='itinerary_versions')
    op.drop_table('itinerary_versions')
    # ### end Alembic commands ###
